---
llm:
  api_base: http://192.168.1.169:8080
#  api_base: https://api.copilot.vk.team
#  api_base: http://127.0.0.1:1234
  api_key: key
  model: Qwen3-Coder-30B-A3B
  log_context: True
  search_limit: 70

embedding:
  api_base: http://192.168.1.169:8080
#  api_base: http://127.0.0.1:1234
  api_key: key
  model: bge-m3
  batch_size: 10        # chunks per request
  concurrency: 48       # parallel requests

chunker:
  max_chunk_size: 1024
  overlap: 256

database:
  host: localhost
  port: 5432
  name: dirtoRAG
  user: postgres
  password: ""

server:
  host: 0.0.0.0
  port: 8888
